# Generated by Django 5.2.3 on 2025-07-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0002_problem_input_problem_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ai_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
